mode: deployment

image:
    repository: otel/opentelemetry-collector-k8s

presets:
    # enables the k8sclusterreceiver and adds it to the metrics pipelines
    clusterMetrics:
        enabled: true
    # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
    kubernetesAttributes:
        enabled: true
    # enables the kubeletstatsreceiver and adds it to the metrics pipelines
    kubeletMetrics:
        enabled: true
    # Enables the filelogreceiver and adds it to the logs pipelines
    logsCollection:
        enabled: true

config:
    exporters:
        otlphttp:
            endpoint: http://loki.sunstrike:3100/otlp
            tls:
                insecure: true
    service:
        pipelines:
            logs:
                exporters: [otlphttp]

