import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "../components/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <div className="">
            <body className="inline-block h-screen w-screen m-0 p-0">
                <div className="fixed align-top max-w-46 h-full">
                    <SideNav></SideNav>
                </div>
                <div id="page" className="block pl-[204px] h-full w-screen bg-black p-auto">
                    {children}
                </div>

            </body>
        </div>
    </html>
  );
}
